version: "3.8"
services: 
  webapi:
    container_name: webapi
    restart: always
    build:
      context: .
      dockerfile: ./ElasticSearch/Dockerfile
    ports:
      - "3000:80"
      - "3001:443"
    environment:
      - DOTNET_ENVIRONMENT=Development
    depends_on: 
      - elasticsearch
    networks: 
      - es-network
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits: 
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks: 
      - es-network
        
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.1.1
    restart: always
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - es-network
  
volumes: 
  esdata:
    driver: local

networks:
  es-network:
    driver: bridge