apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: webapi
  name: webapi
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
    - name: "3001"
      port: 3001
      targetPort: 443
  selector:
    io.kompose.service: webapi
status:
  loadBalancer: {}
